set positional-arguments

sed_inplace := if os() == "macos" { "-i ''" } else { "-i" }

test feature-name:
    devcontainer features test -f {{feature-name}} --skip-autogenerated

test-scenario feature-name scenario-filter:
    devcontainer features test -f {{feature-name}} --filter "{{scenario-filter}}" --skip-autogenerated

unarchive feature-name:
    mv archive/src/{{feature-name}} src/
    mv archive/test/{{feature-name}} test/

archive feature-name:
    mv src/{{feature-name}} archive/src/
    mv test/{{feature-name}} archive/test/

add feature-name:
    mkdir -p src/{{feature-name}} test/{{feature-name}}
    cp templates/bak/src/* src/{{feature-name}}/
    cp templates/bak/test/* test/{{feature-name}}/
    sed {{sed_inplace}} "s/<id>/{{feature-name}}/g" src/{{feature-name}}/*
    sed {{sed_inplace}} "s/<id>/{{feature-name}}/g" test/{{feature-name}}/*
